# Generated by Django 5.2.3 on 2025-06-30 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='listingWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
